[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  SECRETS_SCAN_OMIT_KEYS = "CONTENTFUL_ENVIRONMENT,CONTENTFUL_SPACE_ID"

[[plugins]]
  package = "@netlify/plugin-nextjs"
