[build]
  command = "next build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  SECRETS_SCAN_OMIT_KEYS = "CONTENTFUL_ENVIRONMENT,CONTENTFUL_SPACE_ID"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
